# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36da5411e7852dcb544ec509540d7825d3eb7106b88fdae34148e2ba40c519ff58b3ab646822af5c55cdada41d9d3d5db361c30500b63a5d6962581461cbed4a

test:
  secret_key_base: 434cbacb29c7bcacf6439c8ef0bf8da01647562ed539b53fcf183589aeaf94960436bdb59e45fbc04234ef9a6939534c2c9b7fbab8e45cf2e3b057b10040d0e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
